FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD swagger2-demo-0.0.1-SNAPSHOT.jar app.jar
RUN sh -c 'touch /app.jar'
ENV JAVA_OPTS=""
ENTRYPOINT ["java","-Djava.security.egd=file:mvn package docker:build/dev/./urandom","-jar","/app.jar"]